### ISSUE TITLE
1.19.4 support

### ISSUE THREAD

**Issue by QuanTrieuPCYT** [tr7zw/GraphUtil#6]
The mod currently crashes on 1.19.4 clients. Waiting for an update. Nice mod btw, really useful for debugging.

**Comment by tr7zw** [comment]
Huh, I had in mind that it did work with 1.19.4, but apparently, it was just 1.19.3. Will look into it later.

**Comment by QuanTrieuPCYT** [comment]
Hell yeah.

More info about that: The mod doesn't instantly crash on startup, only when you press Alt+F3 to bring up the modded Graph Bar which crashes the client.

Seems like Mojang did something though, looking forward to a fix!

**Comment by tr7zw** [comment]
> The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: 'void com.mojang.blaze3d.systems.RenderSystem.disableTexture()'

Seems like some part of the render logic got changed/renamed. Nothing too bad.

**Comment by tr7zw** [comment]
Done.

**Comment by QuanTrieuPCYT** [comment]
Great!
